name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/locomate-backend
            git pull origin main
            npm install
            npm rebuild bcrypt
            npx prisma generate
            npx prisma migrate deploy
            sudo rm -rf /var/www/html/admin/*
            sudo cp -r locomate-admin/dist/. /var/www/html/admin/
            sudo mkdir -p /var/www/locomate-landing
            sudo cp -r landing/. /var/www/locomate-landing/
            pm2 delete all
            pm2 start npm --name server -- run dev
            pm2 save
